// DON'T EDIT *** generated by scaneo *** DON'T EDIT //

package model

import "database/sql"

func ScanEvent(r *sql.Row) (Event, error) {
	var s Event
	if err := r.Scan(
		&s.ID,
		&s.Name,
	); err != nil {
		return Event{}, err
	}
	return s, nil
}

func ScanEvents(rs *sql.Rows) ([]Event, error) {
	structs := make([]Event, 0, 16)
	var err error
	for rs.Next() {
		var s Event
		if err = rs.Scan(
			&s.ID,
			&s.Name,
		); err != nil {
			return nil, err
		}
		structs = append(structs, s)
	}
	if err = rs.Err(); err != nil {
		return nil, err
	}
	return structs, nil
}

func ScanEventJson(r *sql.Row) (EventJson, error) {
	var s EventJson
	if err := r.Scan(
		&s.ID,
		&s.Name,
		&s.CategoryID,
		&s.Count1,
		&s.Count2,
		&s.Count3,
		&s.Count4,
		&s.Count5,
		&s.Count6,
		&s.Count7,
		&s.Count8,
		&s.Count9,
		&s.Count10,
	); err != nil {
		return EventJson{}, err
	}
	return s, nil
}

func ScanEventJsons(rs *sql.Rows) ([]EventJson, error) {
	structs := make([]EventJson, 0, 16)
	var err error
	for rs.Next() {
		var s EventJson
		if err = rs.Scan(
			&s.ID,
			&s.Name,
			&s.CategoryID,
			&s.Count1,
			&s.Count2,
			&s.Count3,
			&s.Count4,
			&s.Count5,
			&s.Count6,
			&s.Count7,
			&s.Count8,
			&s.Count9,
			&s.Count10,
		); err != nil {
			return nil, err
		}
		structs = append(structs, s)
	}
	if err = rs.Err(); err != nil {
		return nil, err
	}
	return structs, nil
}

