// DON'T EDIT *** generated by scaneo *** DON'T EDIT //

package model

import "database/sql"

func ScanCategory(r *sql.Row) (Category, error) {
	var s Category
	if err := r.Scan(
		&s.ID,
		&s.Name,
		&s.ImageUrl,
	); err != nil {
		return Category{}, err
	}
	return s, nil
}

func ScanCategorys(rs *sql.Rows) ([]Category, error) {
	structs := make([]Category, 0, 16)
	var err error
	for rs.Next() {
		var s Category
		if err = rs.Scan(
			&s.ID,
			&s.Name,
			&s.ImageUrl,
		); err != nil {
			return nil, err
		}
		structs = append(structs, s)
	}
	if err = rs.Err(); err != nil {
		return nil, err
	}
	return structs, nil
}

func ScanRecipe(r *sql.Row) (Recipe, error) {
	var s Recipe
	if err := r.Scan(
		&s.ID,
		&s.Name,
		&s.CategoryID,
		&s.Count1,
		&s.Count2,
		&s.Count3,
		&s.Count4,
		&s.Count5,
		&s.Count6,
		&s.Count7,
		&s.Count8,
		&s.Count9,
		&s.Count10,
	); err != nil {
		return Recipe{}, err
	}
	return s, nil
}

func ScanRecipes(rs *sql.Rows) ([]Recipe, error) {
	structs := make([]Recipe, 0, 16)
	var err error
	for rs.Next() {
		var s Recipe
		if err = rs.Scan(
			&s.ID,
			&s.Name,
			&s.CategoryID,
			&s.Count1,
			&s.Count2,
			&s.Count3,
			&s.Count4,
			&s.Count5,
			&s.Count6,
			&s.Count7,
			&s.Count8,
			&s.Count9,
			&s.Count10,
		); err != nil {
			return nil, err
		}
		structs = append(structs, s)
	}
	if err = rs.Err(); err != nil {
		return nil, err
	}
	return structs, nil
}

